#端口
server:
  port: 8001
  servlet:
    context-path: /api
#mysql redis
spring:
  datasource:
    username: root
    password: 859635
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sypet?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&serverTimezone=Asia/Shanghai

  redis:
    port: 6379
    host: localhost
    #使用qq邮箱发送邮件
  #  mail:
  #    username:
  #    password:
  #    host: smtp.qq.com
  #    properties:
  #      mail:
  #        smtp:
  #          ssl:
  #            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  #rabbitMQ
  rabbitmq:
    port: 5672
    host: localhost
    username: admin
    password: admin
    virtual-host: /
  #启用dev配置文件
  profiles:
    active: dev

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

#七牛云存储
#qiniu:
#    accessKey:
#    secretKey:
#    bucket:
#    prefix:
logging:
  level:
    com.hth.mapper: debug
